from .pick_cube import solve as solvePickCube
from .stack_cube import solve as solveStackCube
from .peg_insertion_side import solve as solvePegInsertionSide
from .plug_charger import solve as solvePlugCharger
from .push_cube import solve as solvePushCube
from .pull_cube_tool import solve as solvePullCubeTool
from .lift_peg_upright import solve as solveLiftPegUpright
from .pull_cube import solve as solvePullCube
from .place_sphere_my import solve as solvePlaceSphereMy
from .two_step_my_together import solve as solveTwoStep_my_together
from .two_step_my_inbin import solve as solveTwoStep_my_inbin
from .two_step_my_outbin import solve as solveTwoStep_my_outbin
from .table_sort_my import solve as solveTableSort_my
from .table_sort_my_obj0 import solve as solveTableSortObj0_my
from .table_sort_my_obj1 import solve as solveTableSortObj1_my
from .table_sort_my_obj2 import solve as solveTableSortObj2_my
from .table_sort_my_exp1_type1 import solve as solveTableSortExp1Type1
from .table_sort_my_exp1_type2 import solve as solveTableSortExp1Type2
from .table_sort_my_exp1_type3 import solve as solveTableSortExp1Type3
from .table_sort_my_exp1_type4 import solve as solveTableSortExp1Type4
from .table_sort_my_exp1_type5 import solve as solveTableSortExp1Type5
from .table_sort_my_exp1_type6 import solve as solveTableSortExp1Type6